<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddDataToCities extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $cities = array(
            array('id' => '10', 'region_id' => '8', 'name_uz' => 'Nukus shahar', 'name_ru' => 'г. Нукус'),
            array('id' => '12', 'region_id' => '8', 'name_uz' => 'Amudaryo tumani', 'name_ru' => 'Амударьинский район'),
            array('id' => '13', 'region_id' => '8', 'name_uz' => 'Beruniy tumani', 'name_ru' => 'Берунийский район'),
            array('id' => '14', 'region_id' => '8', 'name_uz' => 'Qonliko’l tumani', 'name_ru' => 'Канлыкульский район'),
            array('id' => '15', 'region_id' => '8', 'name_uz' => 'Qorao’zak tumani', 'name_ru' => 'Караузякский район'),
            array('id' => '16', 'region_id' => '8', 'name_uz' => 'Kegeyli tumani', 'name_ru' => 'Кегейлийский район'),
            array('id' => '17', 'region_id' => '8', 'name_uz' => 'Qo’ng’irot tumani', 'name_ru' => 'Кунградский район'),
            array('id' => '18', 'region_id' => '8', 'name_uz' => 'Muynoq tumani', 'name_ru' => 'Муйнакский район'),
            array('id' => '19', 'region_id' => '8', 'name_uz' => 'Nukus tumani', 'name_ru' => 'Нукусский район'),
            array('id' => '20', 'region_id' => '8', 'name_uz' => 'Taxtako’prik tumani', 'name_ru' => 'Тахтакупырский район'),
            array('id' => '21', 'region_id' => '8', 'name_uz' => 'To’rtko’l tumani', 'name_ru' => 'Турткульский район'),
            array('id' => '22', 'region_id' => '8', 'name_uz' => 'Xo’jayli tumani', 'name_ru' => 'Ходжейлийский район'),
            array('id' => '23', 'region_id' => '8', 'name_uz' => 'Chimboy tumani', 'name_ru' => 'Чимбайский район'),
            array('id' => '24', 'region_id' => '8', 'name_uz' => 'Sho’manay tumani', 'name_ru' => 'Шуманайский район'),
            array('id' => '25', 'region_id' => '8', 'name_uz' => 'Ellikqal’a tumani', 'name_ru' => 'Элликкалинский район'),
            array('id' => '26', 'region_id' => '9', 'name_uz' => 'Buxoro shahar', 'name_ru' => 'г. Бухара'),
            array('id' => '27', 'region_id' => '9', 'name_uz' => 'Buxoro tuman', 'name_ru' => 'Бухарский район'),
            array('id' => '28', 'region_id' => '9', 'name_uz' => 'Vobkent tuman', 'name_ru' => 'Вабкентский район'),
            array('id' => '29', 'region_id' => '9', 'name_uz' => 'G’ijduvon tuman', 'name_ru' => 'Гиждуванский район'),
            array('id' => '30', 'region_id' => '9', 'name_uz' => 'Jondor tuman', 'name_ru' => 'Жондорский район'),
            array('id' => '32', 'region_id' => '9', 'name_uz' => 'Kogon tuman', 'name_ru' => 'г. Каган район'),
            array('id' => '33', 'region_id' => '9', 'name_uz' => 'Olot tuman', 'name_ru' => 'Алатский район'),
            array('id' => '34', 'region_id' => '9', 'name_uz' => 'Peshku tuman', 'name_ru' => 'Пешкунский район'),
            array('id' => '35', 'region_id' => '9', 'name_uz' => 'Romitan tuman', 'name_ru' => 'Ромитанский район'),
            array('id' => '36', 'region_id' => '9', 'name_uz' => 'Shofirkon tuman', 'name_ru' => 'Шафирканский район'),
            array('id' => '37', 'region_id' => '9', 'name_uz' => 'Qorako’l tuman', 'name_ru' => 'Каракульский район'),
            array('id' => '38', 'region_id' => '9', 'name_uz' => 'Qorovulbozor tuman', 'name_ru' => 'Караулбазарский район'),
            array('id' => '39', 'region_id' => '10', 'name_uz' => 'Samarqand shahar', 'name_ru' => 'г. Самарканд'),
            array('id' => '40', 'region_id' => '10', 'name_uz' => 'Oqdaryo tumani', 'name_ru' => 'Акдарьинский район'),
            array('id' => '41', 'region_id' => '10', 'name_uz' => 'Bulung’ur tumani', 'name_ru' => 'Булунгурский район'),
            array('id' => '42', 'region_id' => '10', 'name_uz' => 'Jomboy tumani', 'name_ru' => 'Джамбайский район'),
            array('id' => '43', 'region_id' => '10', 'name_uz' => 'Kattaqo’rg’on tumani', 'name_ru' => 'Каттакурганский район'),
            array('id' => '44', 'region_id' => '10', 'name_uz' => 'Kattaqo’rg’on shahar', 'name_ru' => 'г. Каттакурган'),
            array('id' => '45', 'region_id' => '10', 'name_uz' => 'Qo’shrabod tumani', 'name_ru' => 'Кошрабадский район'),
            array('id' => '46', 'region_id' => '10', 'name_uz' => 'Narpay tumani', 'name_ru' => 'Нарпайский район'),
            array('id' => '47', 'region_id' => '10', 'name_uz' => 'Nurobod tumani', 'name_ru' => 'Нурабадский район'),
            array('id' => '48', 'region_id' => '10', 'name_uz' => 'Payariq tumani', 'name_ru' => 'Пайарыкский район'),
            array('id' => '49', 'region_id' => '10', 'name_uz' => 'Pastdarg’om tumani', 'name_ru' => 'Пасдаргомский район'),
            array('id' => '50', 'region_id' => '10', 'name_uz' => 'Paxtachi tumani', 'name_ru' => 'Пахтачийский район'),
            array('id' => '51', 'region_id' => '10', 'name_uz' => 'Samarqand tumani', 'name_ru' => 'Самаркандский район'),
            array('id' => '53', 'region_id' => '10', 'name_uz' => 'Tayloq tumani', 'name_ru' => 'Тайлакский район'),
            array('id' => '54', 'region_id' => '10', 'name_uz' => 'Urgut tumani', 'name_ru' => 'Ургутский район'),
            array('id' => '55', 'region_id' => '11', 'name_uz' => 'Navoiy shahar', 'name_ru' => 'г. Навои'),
            array('id' => '56', 'region_id' => '11', 'name_uz' => 'Karmana tumani', 'name_ru' => 'Карманинский район'),
            array('id' => '57', 'region_id' => '11', 'name_uz' => 'Navbaxor tumani', 'name_ru' => 'Навбахорский район'),
            array('id' => '58', 'region_id' => '11', 'name_uz' => 'Nurota tumani', 'name_ru' => 'Нуратинский район'),
            array('id' => '59', 'region_id' => '11', 'name_uz' => 'Xatirchi tumani', 'name_ru' => 'Хатырчинский район'),
            array('id' => '60', 'region_id' => '11', 'name_uz' => 'Qiziltepa tumani', 'name_ru' => 'Кызылтепинский район'),
            array('id' => '61', 'region_id' => '11', 'name_uz' => 'Konimex tumani', 'name_ru' => 'Канимехский район'),
            array('id' => '62', 'region_id' => '11', 'name_uz' => 'Uchquduq tumani', 'name_ru' => 'Учкудукский район'),
            array('id' => '63', 'region_id' => '11', 'name_uz' => 'Zarafshon shahar', 'name_ru' => 'г.  Зарафшан'),
            array('id' => '64', 'region_id' => '11', 'name_uz' => 'Tomdi tumani', 'name_ru' => 'Тамдынский район'),
            array('id' => '65', 'region_id' => '12', 'name_uz' => 'Andijon shahar', 'name_ru' => 'г. Андижан'),
            array('id' => '66', 'region_id' => '12', 'name_uz' => 'Xonobod shahar', 'name_ru' => 'г. Ханабад'),
            array('id' => '67', 'region_id' => '12', 'name_uz' => 'Andijon tumani', 'name_ru' => 'Андижанский район'),
            array('id' => '68', 'region_id' => '12', 'name_uz' => 'Asaka tumani', 'name_ru' => 'Асакинский район'),
            array('id' => '69', 'region_id' => '12', 'name_uz' => 'Baliqchi tumani', 'name_ru' => 'Балыкчинский район'),
            array('id' => '70', 'region_id' => '12', 'name_uz' => 'Bo’z tumani', 'name_ru' => 'Бозский район'),
            array('id' => '71', 'region_id' => '12', 'name_uz' => 'Buloqboshi tumani', 'name_ru' => 'Булакбашинский район'),
            array('id' => '72', 'region_id' => '12', 'name_uz' => 'Jalolquduq tumani', 'name_ru' => 'Жалакудукский район'),
            array('id' => '73', 'region_id' => '12', 'name_uz' => 'Izboskan tumani', 'name_ru' => 'Избасканский район'),
            array('id' => '74', 'region_id' => '12', 'name_uz' => 'Ulug’nor tumani', 'name_ru' => 'Улугнорский район'),
            array('id' => '75', 'region_id' => '12', 'name_uz' => 'Qo’rg’ontepa tumani', 'name_ru' => 'Кургантепинский район'),
            array('id' => '76', 'region_id' => '12', 'name_uz' => 'Marxamat tumani', 'name_ru' => 'Мархаматский район'),
            array('id' => '77', 'region_id' => '12', 'name_uz' => 'Oltinko’l tumani', 'name_ru' => 'Алтынкульский район'),
            array('id' => '78', 'region_id' => '12', 'name_uz' => 'Paxtaobod tumani', 'name_ru' => 'Пахтаабадский район'),
            array('id' => '79', 'region_id' => '12', 'name_uz' => 'Ho’jaobod tumani', 'name_ru' => 'Ходжаабадский район'),
            array('id' => '80', 'region_id' => '12', 'name_uz' => 'Shaxrixon tumani', 'name_ru' => 'Шахриханский район'),
            array('id' => '82', 'region_id' => '13', 'name_uz' => 'Marg’ilon shahar', 'name_ru' => 'г. Маргилан'),
            array('id' => '83', 'region_id' => '13', 'name_uz' => 'Farg’ona shahar', 'name_ru' => 'г. Фергана'),
            array('id' => '84', 'region_id' => '13', 'name_uz' => 'Quvasoy shahar', 'name_ru' => 'г. Кувасай'),
            array('id' => '85', 'region_id' => '13', 'name_uz' => 'Qo’qon shahar', 'name_ru' => 'г. Коканд'),
            array('id' => '86', 'region_id' => '13', 'name_uz' => 'Bog’dod tumani', 'name_ru' => 'Багдадский район'),
            array('id' => '87', 'region_id' => '13', 'name_uz' => 'Beshariq tumani', 'name_ru' => 'Бешарыкский район'),
            array('id' => '88', 'region_id' => '13', 'name_uz' => 'Buvayda tumani', 'name_ru' => 'Бувайдинский район'),
            array('id' => '89', 'region_id' => '13', 'name_uz' => 'Dang’ara tumani', 'name_ru' => 'Дангаринский район'),
            array('id' => '90', 'region_id' => '13', 'name_uz' => 'Yozyovon tumani', 'name_ru' => 'Язъяванский район'),
            array('id' => '91', 'region_id' => '13', 'name_uz' => 'Oltiariq tumani', 'name_ru' => 'Алтыарыкский район'),
            array('id' => '92', 'region_id' => '13', 'name_uz' => 'Qo’shtepa tumani', 'name_ru' => 'Коштепинский район'),
            array('id' => '93', 'region_id' => '13', 'name_uz' => 'Rishton tumani', 'name_ru' => 'Риштанский район'),
            array('id' => '94', 'region_id' => '13', 'name_uz' => 'So’x tumani', 'name_ru' => 'Сохский район'),
            array('id' => '95', 'region_id' => '13', 'name_uz' => 'Toshloq tumani', 'name_ru' => 'Ташлакский район'),
            array('id' => '96', 'region_id' => '13', 'name_uz' => 'Uchko’prik tumani', 'name_ru' => 'Учкуприкский район'),
            array('id' => '97', 'region_id' => '13', 'name_uz' => 'Farg’ona tumani', 'name_ru' => 'Ферганский район'),
            array('id' => '98', 'region_id' => '13', 'name_uz' => 'Furqat tumani', 'name_ru' => 'Фуркатский район'),
            array('id' => '99', 'region_id' => '13', 'name_uz' => 'O’zbekiston tumani', 'name_ru' => 'Узбекистанский район'),
            array('id' => '100', 'region_id' => '13', 'name_uz' => 'Quva tumani', 'name_ru' => 'Кувинский район'),
            array('id' => '101', 'region_id' => '14', 'name_uz' => 'Angor tumani', 'name_ru' => 'Ангорский район'),
            array('id' => '102', 'region_id' => '14', 'name_uz' => 'Boysun tumani', 'name_ru' => 'Байсунский район'),
            array('id' => '103', 'region_id' => '14', 'name_uz' => 'Denov tumani', 'name_ru' => 'Денауский район'),
            array('id' => '104', 'region_id' => '14', 'name_uz' => 'Jarqo’rg’on tumani', 'name_ru' => 'Джаркурганский район'),
            array('id' => '105', 'region_id' => '14', 'name_uz' => 'Qiziriq tumani', 'name_ru' => 'Кизирыкский район'),
            array('id' => '106', 'region_id' => '14', 'name_uz' => 'Qumqo’rg’on tumani', 'name_ru' => 'Кумкурганский район'),
            array('id' => '107', 'region_id' => '14', 'name_uz' => 'Muzrabot tumani', 'name_ru' => 'Музрабатский район'),
            array('id' => '108', 'region_id' => '14', 'name_uz' => 'Oltinsoy tumani', 'name_ru' => 'Алтынсайский район'),
            array('id' => '109', 'region_id' => '14', 'name_uz' => 'Sariosiyo tumani', 'name_ru' => 'Сариасийский район'),
            array('id' => '110', 'region_id' => '14', 'name_uz' => 'Termiz tumani', 'name_ru' => 'Термезский район'),
            array('id' => '111', 'region_id' => '14', 'name_uz' => 'Termiz shahar', 'name_ru' => 'г. Термез'),
            array('id' => '112', 'region_id' => '14', 'name_uz' => 'Uzun tumani', 'name_ru' => 'Узунский район'),
            array('id' => '113', 'region_id' => '14', 'name_uz' => 'Sherobod tumani', 'name_ru' => 'Шерабадский район'),
            array('id' => '114', 'region_id' => '14', 'name_uz' => 'Sho’rchi tumani', 'name_ru' => 'Шурчинский район'),
            array('id' => '115', 'region_id' => '15', 'name_uz' => 'Oqoltin tumani', 'name_ru' => 'Акалтынский район'),
            array('id' => '116', 'region_id' => '15', 'name_uz' => 'Boyovut tumani', 'name_ru' => 'Баяутский район'),
            array('id' => '117', 'region_id' => '15', 'name_uz' => 'Guliston tumani', 'name_ru' => 'Гулистанский район'),
            array('id' => '118', 'region_id' => '15', 'name_uz' => 'Mirzaobod tumani', 'name_ru' => 'Мирзаабадский район'),
            array('id' => '119', 'region_id' => '15', 'name_uz' => 'Sayxunobod tumani', 'name_ru' => 'Сайхунабадский район'),
            array('id' => '120', 'region_id' => '15', 'name_uz' => 'Sirdaryo tumani', 'name_ru' => 'Сырдарьинский район'),
            array('id' => '121', 'region_id' => '15', 'name_uz' => 'Sardoba tumani', 'name_ru' => 'Сардобинский район'),
            array('id' => '122', 'region_id' => '15', 'name_uz' => 'Xovos tumani', 'name_ru' => 'Хавастский район'),
            array('id' => '123', 'region_id' => '15', 'name_uz' => 'Guliston shahar', 'name_ru' => 'г. Гулистан'),
            array('id' => '124', 'region_id' => '15', 'name_uz' => 'Shirin shahar', 'name_ru' => 'г. Ширин'),
            array('id' => '126', 'region_id' => '15', 'name_uz' => 'Yangiyer shahar', 'name_ru' => 'г. Янгиер'),
            array('id' => '127', 'region_id' => '16', 'name_uz' => 'Urganch shahar', 'name_ru' => 'г. Ургенч'),
            array('id' => '128', 'region_id' => '16', 'name_uz' => 'Bog’ot tumani', 'name_ru' => 'Багатский район'),
            array('id' => '129', 'region_id' => '16', 'name_uz' => 'Gurlan tumani', 'name_ru' => 'Гурленский район'),
            array('id' => '130', 'region_id' => '16', 'name_uz' => 'Xozarasp tumani', 'name_ru' => 'Хазараспский район'),
            array('id' => '131', 'region_id' => '16', 'name_uz' => 'Xiva tumani', 'name_ru' => 'Хивинский район'),
            array('id' => '132', 'region_id' => '16', 'name_uz' => 'Xonqa tumani', 'name_ru' => 'Ханкинский район'),
            array('id' => '133', 'region_id' => '16', 'name_uz' => 'Urganch tumani', 'name_ru' => 'Ургенчский район'),
            array('id' => '134', 'region_id' => '16', 'name_uz' => 'Qo’shko’pir tumani', 'name_ru' => 'Кошкупырский район'),
            array('id' => '135', 'region_id' => '16', 'name_uz' => 'Shovot tumani', 'name_ru' => 'Шаватский район'),
            array('id' => '136', 'region_id' => '16', 'name_uz' => 'Yangiariq tumani', 'name_ru' => 'Янгиарыкский район'),
            array('id' => '137', 'region_id' => '16', 'name_uz' => 'Yangibozor tumani', 'name_ru' => 'Янгибазарский район'),
            array('id' => '138', 'region_id' => '17', 'name_uz' => 'Angren shahar', 'name_ru' => 'г. Ангрен'),
            array('id' => '139', 'region_id' => '17', 'name_uz' => 'Bekobod shahar', 'name_ru' => 'г. Бекабад'),
            array('id' => '140', 'region_id' => '17', 'name_uz' => 'Olmaliq shahar', 'name_ru' => 'г. Алмалик'),
            array('id' => '141', 'region_id' => '17', 'name_uz' => 'Chirchiq shahar', 'name_ru' => 'г. Чирчик'),
            array('id' => '142', 'region_id' => '17', 'name_uz' => 'Bekobod tumani', 'name_ru' => 'Бекабадский район'),
            array('id' => '143', 'region_id' => '17', 'name_uz' => 'Bo’ka tumani', 'name_ru' => 'Букинский район'),
            array('id' => '144', 'region_id' => '17', 'name_uz' => 'Bo’stonliq tumani', 'name_ru' => 'Бостанлыкский район'),
            array('id' => '145', 'region_id' => '17', 'name_uz' => 'Qibray tumani', 'name_ru' => 'Кибрайский район'),
            array('id' => '146', 'region_id' => '17', 'name_uz' => 'Zangiota tumani', 'name_ru' => 'Зангиатинский район'),
            array('id' => '148', 'region_id' => '17', 'name_uz' => 'Quyichirchiq tumani', 'name_ru' => 'Куйичирчикский район'),
            array('id' => '149', 'region_id' => '17', 'name_uz' => 'Oqqo’rg’on tumani', 'name_ru' => 'Аккурганский район'),
            array('id' => '150', 'region_id' => '17', 'name_uz' => 'Oxongaron tumani', 'name_ru' => 'Ахангаранский район'),
            array('id' => '151', 'region_id' => '17', 'name_uz' => 'Parkent tumani', 'name_ru' => 'Паркентский район'),
            array('id' => '152', 'region_id' => '17', 'name_uz' => 'Pskent tumani', 'name_ru' => 'Пскентский район'),
            array('id' => '153', 'region_id' => '17', 'name_uz' => 'O’rtachirchiq tumani', 'name_ru' => 'Уртачирчикский район'),
            array('id' => '154', 'region_id' => '17', 'name_uz' => 'Chinoz tumani', 'name_ru' => 'Чиназский район'),
            array('id' => '155', 'region_id' => '17', 'name_uz' => 'Yuqorichirchiq tumani', 'name_ru' => 'Юкоричирчикский район'),
            array('id' => '156', 'region_id' => '17', 'name_uz' => 'Yangiyo’l tumani', 'name_ru' => 'Янгиюльский район'),
            array('id' => '158', 'region_id' => '18', 'name_uz' => 'Qarshi shahar', 'name_ru' => 'г. Карши'),
            array('id' => '159', 'region_id' => '18', 'name_uz' => 'G’uzor tumani', 'name_ru' => 'Гузарский район'),
            array('id' => '160', 'region_id' => '18', 'name_uz' => 'Qarshi tumani', 'name_ru' => 'Каршинский район'),
            array('id' => '161', 'region_id' => '18', 'name_uz' => 'Kasbi tumani', 'name_ru' => 'Касбинский район'),
            array('id' => '162', 'region_id' => '18', 'name_uz' => 'Koson tumani', 'name_ru' => 'Касанский район'),
            array('id' => '163', 'region_id' => '18', 'name_uz' => 'Kitob tumani', 'name_ru' => 'Китабский район'),
            array('id' => '164', 'region_id' => '18', 'name_uz' => 'Mirishkor tumani', 'name_ru' => 'Миришкорский район'),
            array('id' => '165', 'region_id' => '18', 'name_uz' => 'Muborak tumani', 'name_ru' => 'Мубарекский район'),
            array('id' => '166', 'region_id' => '18', 'name_uz' => 'Nishon tumani', 'name_ru' => 'Нишанский район'),
            array('id' => '167', 'region_id' => '18', 'name_uz' => 'Chiroqchi tumani', 'name_ru' => 'Чиракчинский район'),
            array('id' => '168', 'region_id' => '18', 'name_uz' => 'Shaxrisabz tumani', 'name_ru' => 'Шахрисабзский район'),
            array('id' => '170', 'region_id' => '18', 'name_uz' => 'Qamashi tumani', 'name_ru' => 'Камашинский район'),
            array('id' => '171', 'region_id' => '18', 'name_uz' => 'Dexqonobod tumani', 'name_ru' => 'Дехканабадский район'),
            array('id' => '172', 'region_id' => '18', 'name_uz' => 'Yakkabog’ tumani', 'name_ru' => 'Яккабакский район'),
            array('id' => '173', 'region_id' => '19', 'name_uz' => 'Jizzax shahar', 'name_ru' => 'г. Джизак'),
            array('id' => '174', 'region_id' => '19', 'name_uz' => 'Baxmal tumani', 'name_ru' => 'Бахмальский район'),
            array('id' => '175', 'region_id' => '19', 'name_uz' => 'Do’stlik tumani', 'name_ru' => 'Дустликский район'),
            array('id' => '176', 'region_id' => '19', 'name_uz' => 'G’allaorol tumani', 'name_ru' => 'Галляаральский район'),
            array('id' => '177', 'region_id' => '19', 'name_uz' => 'Jizzax tumani', 'name_ru' => 'Джизакский район'),
            array('id' => '178', 'region_id' => '19', 'name_uz' => 'Zarbdor tumani', 'name_ru' => 'Зарбдорский район'),
            array('id' => '179', 'region_id' => '19', 'name_uz' => 'Zafarobod tumani', 'name_ru' => 'Зафарабадский район'),
            array('id' => '180', 'region_id' => '19', 'name_uz' => 'Zomin tumani', 'name_ru' => 'Зааминский район'),
            array('id' => '181', 'region_id' => '19', 'name_uz' => 'Paxtakor tumani', 'name_ru' => 'Пахтакорский район'),
            array('id' => '182', 'region_id' => '19', 'name_uz' => 'Mirzacho’l tumani', 'name_ru' => 'Мирзачульский район'),
            array('id' => '183', 'region_id' => '19', 'name_uz' => 'Forish tumani', 'name_ru' => 'Фаришский район'),
            array('id' => '184', 'region_id' => '19', 'name_uz' => 'Yangiobod tumani', 'name_ru' => 'Янгиабадский район'),
            array('id' => '185', 'region_id' => '21', 'name_uz' => 'Namangan shahar', 'name_ru' => 'г. Наманган'),
            array('id' => '186', 'region_id' => '21', 'name_uz' => 'Mingbuloq tumani', 'name_ru' => 'Мингбулакский район'),
            array('id' => '189', 'region_id' => '21', 'name_uz' => 'Pop tumani', 'name_ru' => 'Папский район'),
            array('id' => '190', 'region_id' => '21', 'name_uz' => 'Norin tumani', 'name_ru' => 'Нарынский район'),
            array('id' => '191', 'region_id' => '21', 'name_uz' => 'To’raqo’rg’on tumani', 'name_ru' => 'Туракурганский район'),
            array('id' => '192', 'region_id' => '21', 'name_uz' => 'Uychi tumani', 'name_ru' => 'Уйчинский район'),
            array('id' => '194', 'region_id' => '21', 'name_uz' => 'Chortoq tumani', 'name_ru' => 'Чартакский район'),
            array('id' => '195', 'region_id' => '21', 'name_uz' => 'Chust tumani', 'name_ru' => 'Чустский район'),
            array('id' => '196', 'region_id' => '21', 'name_uz' => 'Yangiqo’rg’on tumani', 'name_ru' => 'Янгикурганский район'),
            array('id' => '198', 'region_id' => '22', 'name_uz' => 'Yunusobod tumani', 'name_ru' => 'Юнусабадский район'),
            array('id' => '199', 'region_id' => '22', 'name_uz' => 'Mirobod tumani', 'name_ru' => 'Мирабадский район'),
            array('id' => '200', 'region_id' => '22', 'name_uz' => 'Yakkasaroy tumani', 'name_ru' => 'Яккасарайский район'),
            array('id' => '201', 'region_id' => '22', 'name_uz' => 'Olmazor tumani', 'name_ru' => 'Алмазарский район'),
            array('id' => '202', 'region_id' => '22', 'name_uz' => 'Bektemir tumani', 'name_ru' => 'Бектемирский район'),
            array('id' => '203', 'region_id' => '22', 'name_uz' => 'Yashnobod tumani', 'name_ru' => 'Яшанабадский район'),
            array('id' => '204', 'region_id' => '22', 'name_uz' => 'Chilonzor tumani', 'name_ru' => 'Чиланзарский район'),
            array('id' => '205', 'region_id' => '22', 'name_uz' => 'Uchtepa tumani', 'name_ru' => 'Учтепинский район'),
            array('id' => '207', 'region_id' => '22', 'name_uz' => 'Mirzo Ulug’bek tumani', 'name_ru' => 'Мирзо-Улугбекский район'),
            array('id' => '208', 'region_id' => '22', 'name_uz' => 'Sergeli tumani', 'name_ru' => 'Сергелийский район'),
            array('id' => '209', 'region_id' => '10', 'name_uz' => 'Ishtixon tumani', 'name_ru' => 'Иштиханский район'),
            array('id' => '210', 'region_id' => '9', 'name_uz' => 'Kogon shahar', 'name_ru' => 'г.Когон'),
            array('id' => '211', 'region_id' => '19', 'name_uz' => 'Arnasoy tumani', 'name_ru' => 'Арнасайский район'),
            array('id' => '212', 'region_id' => '22', 'name_uz' => 'Shayxontoxur tumanI', 'name_ru' => 'Шайхантохурский район'),
            array('id' => '214', 'region_id' => '21', 'name_uz' => 'Namangan tumani', 'name_ru' => 'Наманганский район'),
            array('id' => '215', 'region_id' => '21', 'name_uz' => 'Uchqo’rg’on tumani', 'name_ru' => 'Ускурганский район'),
            array('id' => '216', 'region_id' => '21', 'name_uz' => 'Kosonsoy tumani', 'name_ru' => 'Касанский район'),
            array('id' => '217', 'region_id' => '16', 'name_uz' => 'Xiva shahar', 'name_ru' => 'г.Хива'),
            array('id' => '218', 'region_id' => '8', 'name_uz' => 'Taxiatosh', 'name_ru' => ' Тахиатош'),
            array('id' => '219', 'region_id' => '18', 'name_uz' => 'Shaxrisabz shahar', 'name_ru' => 'г. Шахрисабз'),
            array('id' => '220', 'region_id' => '17', 'name_uz' => 'Тошкент тумани', 'name_ru' => 'Тошкент тумани'),
            array('id' => '221', 'region_id' => '17', 'name_uz' => 'Янгийўл шаҳар', 'name_ru' => 'Янгийўл шаҳар'),
            array('id' => '222', 'region_id' => '17', 'name_uz' => 'Оҳангарон шаҳар', 'name_ru' => 'Оҳангарон шаҳар'),
            array('id' => '223', 'region_id' => '17', 'name_uz' => 'Нурафшон шаҳар', 'name_ru' => 'Нурафшон шаҳар')
        );

        DB::table('cities')->insert($cities);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('cities', function (Blueprint $table) {
            //
        });
    }
}
